# Generated by Django 3.1.7 on 2021-03-16 18:57

from django.db import migrations, models
import django_seconds_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('endpoints', '0002_delete_basemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_time', models.DateTimeField(auto_now_add=True, help_text='audio uploaded time')),
                ('duration', django_seconds_field.SecondsField(help_text='audio duration')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
