# Generated by Django 3.1.7 on 2021-03-16 19:13

import django.contrib.postgres.fields
from django.db import migrations, models
import django_seconds_field


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0003_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_time', models.DateTimeField(auto_now_add=True, help_text='audio uploaded time')),
                ('duration', django_seconds_field.SecondsField(help_text='audio duration')),
                ('name', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=100)),
                ('participants', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=None), size=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
