# Generated by Django 3.1.7 on 2021-03-18 17:28

import django.contrib.postgres.fields
from django.db import migrations, models
import django_seconds_field


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0005_audiobook'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_time', models.DateTimeField(auto_now_add=True, help_text='audio uploaded time')),
                ('duration', django_seconds_field.SecondsField(help_text='audio duration')),
                ('type', models.IntegerField(choices=[(1, 'Song'), (2, 'Podcast'), (3, 'Audiobook')])),
                ('name', models.CharField(max_length=100)),
                ('host', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('narrator', models.CharField(blank=True, max_length=100, null=True)),
                ('participants', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=None), blank=True, null=True, size=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Audiobook',
        ),
        migrations.DeleteModel(
            name='Podcast',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
