# Generated by Django 3.1.7 on 2021-03-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0006_auto_20210318_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='type',
            field=models.IntegerField(choices=[('song', 'Song'), ('podcast', 'Podcast'), ('audiobook', 'Audiobook')]),
        ),
    ]
