# Generated by Django 3.1.7 on 2021-03-23 19:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0008_auto_20210323_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='participants',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=10),
        ),
    ]
